String.toLocaleString({
    
	"en": {
		"%game-intro"           : "Join tiles and destroy <strong>EMPIRE!</strong>",
		"%restart-button"       : "New Game",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Try again",
		"%game-won"             : "You win!",
		"%game-over"            : "Game over!",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%credits"              : "Star Wars icons by <a href=\"http://sensibleworld.com/news/more-free-star-wars-icons/\" title=\"Free Star Wars Icons by Sensible World\">Jory Raphael</a>.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-STARWARS #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : 'stormtrooper',
    '%4'                    : 'super trooper',
    '%8'                    : 'darth vader',
    '%16'                   : 'TIE fighter',
    '%32'                   : 'x-wing',
    '%64'                   : 'millennium falcon',
    '%128'                  : 'at-at all terrain armored transport',
    '%256'                  : 'c-3po protocol droid',
    '%512'                  : 'r2-d2 astromech droid',
    '%1024'                 : 'yoda',
    '%2048'                 : 'death star',
		'%s0'                   : 'trooper',
    '%s4'                   : 's.trooper',
    '%s8'                   : 'vader',
    '%s16'                  : 'TIE',
    '%s32'                  : 'x-wing',
    '%s64'                  : 'falcon',
    '%s128'                 : 'at-at',
    '%s256'                 : 'c-3po',
    '%s512'                 : 'r2-d2',
    '%s1024'                : 'yoda',
    '%s2048'                : 'death star'
	},
	
	"it": {
		"%game-intro"           : "Unisci le tessere e distruggi l&#x27;<strong>IMPERO!</strong>",
		"%restart-button"       : "Nuova Partita",
		"%keep-playing-button"  : "Continua",
		"%retry-button"         : "Riprova",
		"%game-won"             : "Hai vinto!",
		"%game-over"            : "Hai perso!",
		"%game-explanation"     : "<strong class=\"important\">Come giocare:</strong> Usare i <strong>tasti freccia</strong> per muovere le tessere. Quando due tessere con lo stesso simbolo si scontrano c&#x27;&egrave; la <strong>promozione!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Nota:</strong> Questo sito &egrave; uno spin-off della versione ufficiale di <a href=\"http://git.io/2048\">2048</a> creata da <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%tile-legend"          : "<strong class=\"important\">Legenda Tessere:</strong>",
		"%credits"              : "Icone Star Wars di <a href=\"http://sensibleworld.com/news/more-free-star-wars-icons/\" title=\"Free Star Wars Icons by Sensible World\">Jory Raphael</a>.",
		"%tweet1"               : "Ho raggiunto \"",
		"%tweet2"               : "\" a 2048-STARWARS #2048game",
		'%2'                    : 'truppa d\'assalto',
    '%4'                    : 'super truppa',
    '%8'                    : 'dart fener',
    '%16'                   : 'TIE fighter',
    '%32'                   : 'x-wing',
    '%64'                   : 'millennium falcon',
    '%128'                  : 'at-at trasporto corazzato',
    '%256'                  : 'c-3po droide protocollare',
    '%512'                  : 'r2-d2 astrodroide',
    '%1024'                 : 'yoda',
    '%2048'                 : 'morte nera',
		'%p0'                    : 'truppa',
    '%p4'                    : 's.truppa',
    '%p8'                    : 'fener',
    '%p16'                   : 'TIE',
    '%p32'                   : 'x-wing',
    '%p64'                   : 'falcon',
    '%p128'                  : 'at-at',
    '%p256'                  : 'c-3po',
    '%p512'                  : 'r2-d2',
    '%p1024'                 : 'yoda',
    '%p2048'                 : 'morte nera'
	}

});